-- AlterTable
ALTER TABLE "Client" ALTER COLUMN "amountDue" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Reminder" ALTER COLUMN "amountDue" DROP NOT NULL,
ALTER COLUMN "amountDue" SET DATA TYPE DOUBLE PRECISION;
